viewvc/viewvc

- conf/viewvc.conf.dist
- lib/vcauth/svnauthz/__init__.py
- lib/viewvc.py
Presenting repositories as a flat list may e.g. lead to name clashes,
as was mentioned before (like in #58). This changeset allows root names
to contain slashes, with the purpose of presenting repositories in a
structured way. One way of using this, is simply by specifying a slash
in the 'svn_roots', 'cvs_roots' or 'renamed_roots' configuration. Another
way is with the extended 'root_parents' mechanism, where each root parent
can (optionally) be configured with a 'context' to use for the
parent's set of repositories.
This change is meant to be fully backwards compatible. In order to
prevent matches with valid (Windows) path names, the optional 'root
parents' context is specified with the '=' character. The 'root as url
component' mechanism has to look a bit harder for a match with a known …
> Allow root names to have a context

- lib/viewvc.py
This fix issue #176 , with drop Python 2.6 dependency. unlike for 1.1.x branch, this uses '//' (floor division) operator.
> fix issue #176: allow TZ offset with minutes piece (for master branch)

- lib/vclib/svn/svn_ra.py
In swig Python bindings, wrappers for client, delta, diff, fs, ra, repos
APIs which require svn_stream_t * treat 'stream' parameter as file like
object regardlessly and wrap by using svn_swig_py_make_stream().
This behavor introduced Subversion r852660, before Subversion 1.3.0.
https://svn.apache.org/viewvc/subversion/tags/1.3.0/subversion/bindings/swig/include/svn_types.swg?revision=852660&view=markup#l336
https://svn.apache.org/viewvc?view=revision&revision=852660
So it is redundant to pass svn.Stream object to svn.client.svn_client_cat()
This PR reduce redandant wrap by passing file object created by using os.fdopen()
(This PR may conflict PR #159)
> reduce redundant wrap for svn_stream_t in lib/vclib/svn/svn_ra.py

- bin/make-database
This is re-created PR of #161, expected to fix issue #141 and #182.
Using process.Popen class to communicate child process instead of popen2.Popen3 and os.popen to avoid using shell to parse argments string.
I only tested on Python 2.7 and Python 3.7 on FreeBSD 11, but I expect it to work on Python 2.4+.
> Not to use shell to communicate to decendant process in bin/make-database

- lib/viewvc.py
As the caller of viewvc.run_viewvc() does't expect that the server output
stream when the function returns.  However the text wrapper object created
in get_writeready_server_file() closed the stream when viewvc.run_viewvc()
returned, by the destructor of the wrapper object.  That's why
StandAloneServer reported ValueError Exception.  So we use custom wrapper
object not to close underlaid stream when the close() is called or the
object is removed.
* lib/viewvc.py
(TextIOwrapper_noclose):
New child class of io.TextIOWrapper. This never call close() on
underlaid stream.
(get_writeready_server_file):
Use TextIOwrapper_noclose() instead of io.TextIOWrapper.
> issue #214: Fix exception after requests on StandaloneServer

- lib/vcauth/svnauthz/__init__.py
- Import `ConfigParser` from `configparser` instead of `ConfigParser` since that is how to do it in Python 3.
> Fix svnauthz to work in Python 3

- bin/svndbadmin
The return type of the map() function has changed in Python 3.
> Fixed error due to changed return type of map() function in Python 3

- lib/common.py
- lib/sapi.py
- lib/viewvc.py
While here, try to fix problems with bytes/str streams, too.
* `lib/common.py`: (print_exception_data): Don't escape strings -- let callers manage that.
* `lib/sapi.py`: (start_response): Add a message when raising ServerUsageError().
* `lib/viewvc.py`: (view_error): When generating error output through the template system, don't escape error strings.  But if we fall back to the print-to-stream direct approach, do.
> issue #257: Try to avoid double-HTML-escaping error information

- CHANGES
- lib/vclib/ccvs/ccvs.py
It seems some CVS implementation can produce RCS diff outputs that
add an incomplete line which is not terminated by LF code.
However our code didn't care whether the lines are complete or not.
To fix it, we treat "text" in StreamText, without removing trailing LF code.
* lib/vclib/ccvs/ccvs.py
(CCVSRepository.openfile):
Connect contents of StreamText without completion of LF.
(_msplit): New.
(StreamText.d_command, StreamText.a_command): Be stricter.
(StreamText.__init__, StreamText.command):
Don't assume LF code for each end of lines.
> issue #272: ccvs module: Fix issue on checkout caused by adding incomplete line.

- CHANGES
- lib/vclib/ccvs/ccvs.py
* lib/vclib/ccvs/ccvs.py
(CCVSRepository.openfile):
Connect contents of StreamText without completion of LF.
(_msplit): New.
(StreamText.d_command, StreamText.a_command): Be stricter.
(StreamText.__init__, StreamText.command):
Don't assume LF code for each end of lines.
* CHANGES
Note this change.
> issue #272: ccvs module: Fix the issue on checkout caused by adding incomplete line.

- lib/viewvc.py
This is my first ever pull-request on GitHub so please be gentle with me:)
The 'Revision Graph' for a CVS file throws the following exception:
```
File "/var/lib/viewvc/lib/viewvc.py", line 5524, in main
request.run_viewvc()
File "/var/lib/viewvc/lib/viewvc.py", line 457, in run_viewvc
self.view_func(self)
File "/var/lib/viewvc/lib/viewvc.py", line 3339, in view_cvsgraph
generate_page(request, "graph", data)
File "/var/lib/viewvc/lib/viewvc.py", line 1024, in generate_page
template.generate(server_fp, data)
File "/var/lib/viewvc/lib/ezt.py", line 347, in generate
self._execute(self.program, fp, ctx)
File "/var/lib/viewvc/lib/ezt.py", line 524, in _execute
method(method_args, fp, ctx, filename, line_number)
File "/var/lib/viewvc/lib/ezt.py", line 540, in _cmd_print
fp.write(chunk) …
```
> Fix 'Revision Graph' for CVS repository to work with Python 3

- lib/common.py
- lib/vclib/ccvs/bincvs.py
- lib/vclib/svn/svn_repos.py
- lib/viewvc.py
Python2's `cmp()` function no longer exists in Python3, so when we converted to Python3 we reproduced the seemingly relevant bits of `cmp()` as a utility method.  Unfortunately, the naive suggestion from Python's own upgrade docs:
def cmp(a, b):
return (a > b) - (a < b)
...is a bit *too* naive.  Python2's `cmp()` supports `None` input values as well as comparisons between differing types of input values.  We don't need the latter, but it seems in some cases we do need the former.  So this change trades multiple replicas of the naive `cmp()` workaround for a single shared slightly-less-naive implementation that handles `None` inputs the way Python2's `cmp()` does.
> Fix issue #288: cmp() workaround cannot handle None input

- lib/vclib/__init__.py
- lib/viewvc.py
When we ported ViewVC into Python 3,  we use cmp_to_key() function to porting old usage of sorted() / list.sort() function into Python 3 style sorting using key keyword parameter.  However it has disadvantage in performance.
With these commits, I rewrote those cmp functions based key function into native key functions.
> Follow up to issue #288: Use native key function in sort in viewvc.py

- lib/vclib/svn/svn_ra.py
- lib/vclib/svn/svn_repos.py
We used `cmp()` for sorting by using `list.sort()` or `sorted()` functions in Python 2, and we rewrite it for sorting functions in Python 3 by using `functools.cmp_to_key()`.  However it can be simple if we can write the `key` function for sorting which provides a sort key retrieving from each sorting items directly.
In the case in `svn_ra.py`, we were sorting the paths both in bytes and str form by using function `_compare_paths()` as comparison function for `list.sort()`.  However it can be rewritten by using sorting function with `split()` function as a key function for sorting().  As they were the only usage of `_compare_paths()`,   we can remove the function `_compare_paths()` after replacing it.
> Follow up to issue #288: Remove _compare_paths() to reduce the use of cmp()

- lib/vclib/ccvs/bincvs.py
- lib/vclib/ccvs/ccvs.py
In bincvs.py and ccvs.py, we used _logsort_date_cmp() and
_logsort_rev_cmp() as cmp parameter for list.sort() method in Python 2,
for sorting CVS logs.  However it can be done by using key parameter for
list.sort(), with operator.attrgetter(), as "Sorting HOW TO"[1] document
shows.
So we use it and then remove _logsort_date_cmp and _logsort_rev_cmp
functions.
[1] https://docs.python.org/3/howto/sorting.html
* lib/vclib/ccvs/bincvs.py
(_logsort_date_cmp, _logsort_rev_cmp): Removed.
* lib/vclib/ccvs/bincvs.py (BinCVSRepository.itemlog),
lib/vclib/ccvs/ccvs.py (CCVSRepository.itemlog):
Use operator.attrgetter() as key parameter for sorting.
> Follow up to issue #288: Remove _logsort_date_cmp and _logsort_rev_cmp to reduce the use of cmp()

- conf/viewvc.conf.dist
- lib/config.py
- lib/vclib/__init__.py
- lib/viewvc.py
* `conf/viewvc.conf.dist`
(`utilities.max_context`):
New option
(`options.diff_format`):
In comment, excuse "Full human readable" is not truely "full"
* `lib/config.py`
(`Config.set_defaults`):
Set default value for new option "utilities.max_context"
* `lib/vclib/__init__.py`
(`_diff_args`):
Remove special case of options["context"] is None. It should be set an integer value now.
* `lib/viewvc.py` 
(`DiffDescription.__init__`, `DiffDescription.get_content_diff`,
`DiffDescription.get_prop_diff`):
Use None instead of -1 for the flag DiffDescription.context is not set.
(`DiffDescription.__init__`):
Set config "`utilities.max_context`" value as context option value for "Full human readable" diff format.
> issue #293: Make diff --unified option parameter configurable.

- lib/ezt.py
- lib/vclib/__init__.py
- lib/vclib/svn/svn_repos.py
- lib/viewvc.py
The problems were:
1. `get_line` parameter for `DiffDescription._get_diff()` should be a function that returns a list of `str`, but we passed a function that returns a list of `bytes`.
2. In `ezt.py`,  the type of return value `_get_value()` should not be a generator object, but there were some cases they were.
I couldn't determine which shoud be fixed in 2. case,  ezt.py or its caller.  However as the former is easier, I'd taken it.
> Issue #275: Fix unified and side-by-side diff view in the case hr_intraline = 1

- bin/standalone.py
* bin/standalone.py (ViewVCHTTPRequestHandler.run_viewvc): Make a copy of config and pass it.
> standalone: Allow config overlay.

- lib/cvsdb.py
Later versions of Python (at least 3.6) enclose the whole regular expression in
(?s:.....)\Z which is also not understood by MySQL. Remove ?s: and replace
\Z with '$'.
Could possibly be integrated in #213 / #259.
> Fix regular expression returned by fnmatch.translate

- bin/cvsdbadmin
- conf/viewvc.conf.dist
- lib/common.py
- lib/config.py
- lib/vclib/__init__.py
- lib/vclib/ccvs/__init__.py
- lib/vclib/ccvs/bincvs.py
- lib/vclib/ccvs/ccvs.py
- lib/vclib/svn/__init__.py
- lib/vclib/svn/svn_ra.py
- lib/vclib/svn/svn_repos.py
- lib/viewvc.py
This introduces per-repository path encoding.
It allows non-ascii repository root paths in locale encoding for both of CVS repositories and Subversion Repositories.  Also it is used relative paths from the repository root file paths in CVS repos to represent them as Unicode.
~~This is still work in progress,  at least I've not fixed the code to call cvsgraph, yet.~~
> issue #109: Introduce path encoding for repositories.

- lib/vclib/__init__.py
- lib/vclib/ccvs/bincvs.py
- lib/vclib/ccvs/ccvs.py
- lib/vclib/svn/svn_ra.py
- lib/vclib/svn/svn_repos.py
- lib/viewvc.py
In revision diff view, ViewVC should show the diff as UTF-8 encoded Unicode HTML, by transcoding if the file contents is encoded in some encoding other than UTF-8 or ASCII. On the other hand, with generate patch mode, ViewVC should provide a raw diff without transcoding.
Those were not done because vclib._diff_fp(), which is used in diff view without highlighting of intraline changes and generate patch mode, always decoded the file content as UTF-8.
With this commit, we add a new argument to specify the encoding to decode the diff stream, and make the code path to handle the diff content without decoding/encoding, includes vclib._diff_fp().
To accomplish it, we also add a new argument "is_text" to rawdiff() method in vclib.Repository base class and its discendants.
* lib/vclib/__init__.py …
> issue #301: Fix content encoding handling on diff view and on patch.

- lib/vclib/__init__.py
- lib/vclib/ccvs/bincvs.py
- lib/vclib/svn/svn_ra.py
- lib/vclib/svn/svn_repos.py
In vclib.Repository abstract class, rootpath() was defined as a method, however its implementation in subclasses were all broken: each __init__() methods of subclasses substitute self.rootpath method with rootpath paramer value passed by caller.  Also users of vclib.Repository class already uses the value of Repository.rootpath instead of return value of Repository.rootpath().
So we turn Repository.rootpath method into required attribute.
* lib/vclib/__init__.py (Repository): Add description for required attribute(s) in doc string. (Repository.rootpath): Remove method definition.
* lib/vclib/ccvs/bincvs.py (BaseCVSRepository.rootpath): Remove method definition.
* lib/vclib/svn/svn_ra.py (RemoteSubversionRepository.rootpath): Remove method definition.
* lib/vclib/svn/svn_repos.py …
> issue #303: vclib.Repository: make rootpath simple attribute.

- bin/standalone.py
- lib/common.py
- lib/config.py
Before Python 3.7, config.Config instance object cannot be copied by using copy.deepcopy() because it owns instance objects of configparser.ConfigParser as a member, which cannot be copied by using copy.deepcopy().
This is a workaround for it. It also reduces overhead of copy operation.
* lib/config.py
(Config.copy):
New function to hide how to copy this instance object.
(CustomParser in Config.load_config):
New private class.
(Config.load_config):
Use CustomParser instead of configparser.ConfigParser.
* lib/common.py (get_repos_encodings),
bin/standalone.py (ViewVCHTTPRequestHandler.run_viewvc):
Use above to copy config.Config instance.
* lib/common.py (),  bin/standalone.py ():
Don't import unused "copy" module.
Found by: @kberry
> issue #326: Allow copy config.Config instance on Python 3.6

- lib/vcauth/forbidden/__init__.py
- lib/vcauth/forbiddenre/__init__.py
Bare `map()` statements without a wrapping `list()` leave consumable iterables that don't survive multiple traversals.  Fix this oversight.
While here, also fix the problems caused with whitespace-only members of the input list, e.g.:
```
forbidden = matthew, mark,     , luke, john
```
> issue 333: Listify configured forbidden paths/regexps

- lib/viewvc.py
* `lib/viewvc.py (view_revision)`: Avoid decoding a property value we already know to be a unicode string.
> Issue #336: AttributeError: 'str' object has no attribute 'decode'

- lib/vclib/svn/svn_ra.py
- lib/vclib/svn/svn_repos.py
- lib/viewvc.py
* lib/vclib/svn/svn_repos.py (LocalSubversionRepository.get_symlink_target): Fix type of pathspec.
* lib/vclib/svn/svn_ra.py (RemoteSubversionRepository.get_symlink_target): Fix type of pathspec.
* lib/viewvc.py (generate_tarball): pass symlink_target as bytes, explicitly.
Found by: @ddfourni1 on github
> issue #344: Fix symlinks in tar

- lib/viewvc.py
* lib/viewvc (diff_parse_headers): Care for the case when date1 or date2 is None.
Found by @GeekishPedant on GitHub
> issue #346: Fix exceptions on patch generation when two revision have no diff.

- lib/vclib/svn/svn_repos.py
This is a cherry-pick of commit 3098a69 .
The current 1.1.x code is broken anyway:
```
File "/usr/lib/viewvc/lib/vclib/svn/svn_repos.py", line 392, in _sigterm_handler
sys.exit(-1)
NameError: global name 'sys' is not defined
```
You can see a full backtrace, although from an earlier version, at http://svn.savannah.gnu.org/viewvc/freefont/trunk/freefont/sfd/FreeSerif.sfd?view=log .
> 1.1.x: Backport 3098a69

- lib/vclib/ccvs/bincvs.py
ViewVC has historically allowed as a "CVS root parent" both:
- a directory in which distinct CVS repositories (each with their own `CVSROOT/` subdir) are stored.
- a CVS "monorepo", which is a single repository but serves practically as a collection of many distinct projects.
A prior change partially limited this interpretation to only the former situation.  We restore support for the second here.
> Partially revert 14e7719 to restore 1.2 root parent behavior

- INSTALL
- bin/standalone.py
The htpasswd support for standalone.py using crypt or fcrypt module was very limited, and crypt module itself has been obsoleted since Python 3.11.  So we use passlib[1] package available from PyPI.
[1] https://pypi.org/project/passlib/
> issue #361: standalone.py: Use passlib for htpasswd support

- .gitignore
- CHANGES
- conf/viewvc.conf.dist
- lib/viewvc.py
The "image" view behaves like the "co" view, but restricts itself to only serving up the content of web-friendly image files (JPEG, GIF, PNG).  It is disabled by default.
The "markup" view of such files will now prefer the "image" view when generated the ViewVC URL used as the value of the `<img src="..."` attribute, but will fallback to "co" if that's an allowed view and "image" is not.
> issue 360: Introduce new "image" view

- lib/viewvc.py
- templates/default/diff.ezt
Avoid displaying the "Generate patch" link when looking at a (Subversion) directory's diff view.  And at the implementation of the patch view, raise a quick exception if that view is used with a non-file target.
> issue 370: Disallow patch view on directories

- INSTALL
As I wrote in issue [#241 comment](https://github.com/viewvc/viewvc/issues/241#issuecomment-3109883560) we should describe DBMS parameter settings for large index key length.
Although those conditions are satisfied by default,  they can be changed not to be satisfied.
> INSTALL: Add RDBMS settings requirement for commits DB

- bin/db/cvsdbadmin
- bin/db/loginfo-handler
- bin/db/svndbadmin
- bin/standalone.py
- lib/accept.py
- lib/common.py
- lib/config.py
- lib/cvsdb.py
- lib/dbi.py
- lib/ezt.py
- lib/sapi.py
- lib/vclib/__init__.py
- lib/vclib/ccvs/bincvs.py
- lib/vclib/ccvs/blame.py
- lib/vclib/ccvs/ccvs.py
- lib/vclib/ccvs/rcsparse/common.py
- lib/vclib/ccvs/rcsparse/debug.py
- lib/vclib/ccvs/rcsparse/parse_rcs_file.py
- lib/vclib/ccvs/rcsparse/run-tests.py
- lib/vclib/svn/svn_ra.py
- lib/vclib/svn/svn_repos.py
- lib/viewvc.py
- tools/check-code-formatting
- viewvc-install
As much as possible, use f-strings instead of %-formatting for string interpolation, being careful not to disturb MySQL and date/time formatting placeholders.  Selectively replace some string concatenation with f-strings, as well.
Unrelated drive-by fixes included, also:
- Remove unused `lib/common.py:cmp()` function
- Properly handle `lib/vclib/ccvs/ccvs.py:BlameSource.__init__(..., opt_rev=None)`
> Begin a universal conversion to f-strings

- bin/cgi/iis/viewvc.cgi
- bin/cgi/viewvc.cgi
- lib/sapi.py
- viewvc-install
Before dropping `cgi` module from lib/sapi.py,  I propose dropping sapi.CgiServer for simplify by using wsgiref.handler.CGIHandler and wsgiref.handler.IISCGIHandler in viewvc.cgi.
Although I've added bin/cgi/iis/viewvc.cgi for IIS server,  I've not tested.
> A part of Issue #385: Drop sapi.CgiServer

- docs/upgrading-howto.html
Updating docs/upgrading-howto.html for describing about bin/cgi/iis/viewvc.cgi.
> upgrading-howto: describe separation of viewvc.cgi for IIS server
